### ISSUE TITLE
Error on 1.16 : coudnt make the config

### ISSUE THREAD

**Issue by oblx** [runescapejon/CrazyFeet-Sponge#21]
Hi, I keep getting this message whenever I start my server with latest crazyfeet update : 

```
[09:01:43 ERROR] [crazyfeetsponge]: coudnt make the config
java.lang.NullPointerException: null
        at me.runescapejon.CrazyFeet.CrazyFeet.loadConfig(CrazyFeet.java:460) ~[CrazyFeet.class:?]
        at me.runescapejon.CrazyFeet.CrazyFeet.onGamePreInitialization(CrazyFeet.java:129) ~[CrazyFeet.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_CrazyFeet_onGamePreInitialization39.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.10]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:433) ~[SpongeEventManager.class:1.12.2-7.1.10]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:478) ~[SpongeEventManager.class:1.12.2-7.1.10]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:259) ~[SpongeImpl.class:1.12.2-7.1.10]
        at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:267) ~[SpongeImpl.class:1.12.2-7.1.10]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:135) ~[SpongeVanilla.class:1.12.2-7.1.10]
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpj000$vanilla$onServerLoad(SourceFile:2235) ~[nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:117) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) ~[MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]

```

In plugin folder  `config/crazyfeetsponge`  a populated `language.conf (15kb)` is created however there is only an empty `configuration.conf (0kb)`. Is there something I am doing wrong while updating from 1.14 ?

**Comment by runescapejon** [comment]
What sponge version do you have installed?

**Comment by oblx** [comment]
You got it 👍 
I used `1.12.2-7.1.10` and by switching to `1.12.2-7.3.0` error vanished.

My bad for not thinking to update sponge server as well as plugins 🤐 

And thanks for the quick answer !
