### ISSUE TITLE
[ERROR]:Double/Primary Click Error in crazymenu

### ISSUE THREAD

**Issue by Tollainmear** [runescapejon/CrazyFeet-Sponge#7]
Hi, i found a ERROR REPORT when i double click the Icon in the CrazyMenu,Something like that : )

````
[15:44:46] [Server thread/ERROR] [Sponge/]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=crazyfeetsponge, name=CrazyFeetSponge, version=1.6, description=CrazyFeet Ported over to Sponge, authors=[runescapejon], source=D:\minecraft\Sponge-1.10.2\mods\crazyfeet-sponge.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_144]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_144]
	at me.runescapejon.CrazyFeet.Commands.GuiCommand.onInventoryClick(GuiCommand.java:43) ~[GuiCommand.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_GuiCommand_onInventoryClick18.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$30(PacketFunction.java:678) ~[PacketFunction.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:161) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2039]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[15:44:46] [Server thread/ERROR] [Sponge/]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=crazyfeetsponge, name=CrazyFeetSponge, version=1.6, description=CrazyFeet Ported over to Sponge, authors=[runescapejon], source=D:\minecraft\Sponge-1.10.2\mods\crazyfeet-sponge.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_144]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_144]
	at me.runescapejon.CrazyFeet.Commands.GuiCommand.onInventoryClick(GuiCommand.java:43) ~[GuiCommand.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_GuiCommand_onInventoryClick18.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$30(PacketFunction.java:678) ~[PacketFunction.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:161) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2039]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[15:44:47] [Server thread/ERROR] [Sponge/]: Could not pass ClickInventoryEvent$Double$Impl to Plugin{id=crazyfeetsponge, name=CrazyFeetSponge, version=1.6, description=CrazyFeet Ported over to Sponge, authors=[runescapejon], source=D:\minecraft\Sponge-1.10.2\mods\crazyfeet-sponge.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_144]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_144]
	at me.runescapejon.CrazyFeet.Commands.GuiCommand.onInventoryClick(GuiCommand.java:43) ~[GuiCommand.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_GuiCommand_onInventoryClick18.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$30(PacketFunction.java:678) ~[PacketFunction.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:161) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2039]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[15:44:48] [Server thread/ERROR] [Sponge/]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=crazyfeetsponge, name=CrazyFeetSponge, version=1.6, description=CrazyFeet Ported over to Sponge, authors=[runescapejon], source=D:\minecraft\Sponge-1.10.2\mods\crazyfeet-sponge.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_144]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_144]
	at me.runescapejon.CrazyFeet.Commands.GuiCommand.onInventoryClick(GuiCommand.java:43) ~[GuiCommand.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_GuiCommand_onInventoryClick18.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$30(PacketFunction.java:678) ~[PacketFunction.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:161) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2039]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]`
```

**Comment by JoeSGT** [comment]
your using an outdated version dude 
https://ore.spongepowered.org/runescapejon/CrazyFeetSponge/versions/1.8 
update to 1.8 and see if the problem still happens

**Comment by Tollainmear** [comment]
Oh,I'm not sure what went wrong，ive tried several times to download Ur plugin(Ver1.8)from ore,but everytimes i click continue，i was jumped to the home page. So if its convenint,could u upload the latest version to the githut's release page?
Thx!   ;)

**Comment by Tollainmear** [comment]
ummm sorry to say that
ive download the latest version of crazyfeet from ORE,but the file i got was signed "version": "1.6" in <mcmod.info>with latest edit in2017/7/17.
So,im sure that ore was wrong with the management of plugins(i tried with two different explore)...........

**Comment by runescapejon** [comment]
https://github.com/runescapejon/CrazyFeet-Sponge/releases/tag/1.8
sorry i uploaded the wrong jar on ore site going to fix that but there the github release
EDIT: just fixed the ore site version

**Comment by Tollainmear** [comment]
there was still a ERROR REPORT while i double(or triple) click the icons in crazymenu.
`````
[11:27:37] [Server thread/ERROR] [Sponge/]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=crazyfeetsponge, name=CrazyFeetSponge, version=1.8, description=CrazyFeet Ported over to Sponge, authors=[runescapejon], source=D:\minecraft\Sponge-1.10.2\mods\crazyfeet-sponge (1).jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_144]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_144]
	at me.runescapejon.CrazyFeet.Commands.GuiCommand.onInventoryClick(GuiCommand.java:45) ~[GuiCommand.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_GuiCommand_onInventoryClick20.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$30(PacketFunction.java:678) ~[PacketFunction.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:161) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2039]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
[11:27:37] [Server thread/ERROR] [Sponge/]: Could not pass ClickInventoryEvent$Double$Impl to Plugin{id=crazyfeetsponge, name=CrazyFeetSponge, version=1.8, description=CrazyFeet Ported over to Sponge, authors=[runescapejon], source=D:\minecraft\Sponge-1.10.2\mods\crazyfeet-sponge (1).jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source) ~[?:1.8.0_144]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_144]
	at me.runescapejon.CrazyFeet.Commands.GuiCommand.onInventoryClick(GuiCommand.java:45) ~[GuiCommand.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_GuiCommand_onInventoryClick20.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) ~[SpongeModEventManager.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$30(PacketFunction.java:678) ~[PacketFunction.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322) [PacketPhase.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-2202-5.1.0-BETA-2039]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:161) [PacketUtil.class:1.10.2-2202-5.1.0-BETA-2039]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjc000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by runescapejon** [comment]
Sorry I'm unable to reproduce the problem please tell me what sponge version your on
and do you have inventorytweaks mod installed on your server?

**Comment by Tollainmear** [comment]
oh sorry to reply so late,And maybe you got the point........
i test the crazyfeet on MCserver1.10.2(Sponge api5.2.0),And i really installed the inventorytweaks........so....The problem is becaused of the inventorytweak mod?

but there be none problem with virtualchest0.3.8 ......................

**Comment by runescapejon** [comment]
please go on your server and do 
`/sponge version`  and tell me the information it say
and if you have inventorytweaks on the server! then it's very very bad because people can take out items out of the gui 
make sure you only have inventoryweaks mod in your client NOT server!

**Comment by iLefty** [comment]
1.10.2-2202-5.1.0-BETA-2039
His Sponge version. 
This is a very old version, you should upgrade.

**Comment by Tollainmear** [comment]
Thx for reply 

ill check it

**Comment by Tollainmear** [comment]
SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-c675e80
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2558
    Minecraft Forge: 12.18.3.2422

Sorry to reply so late!

**Comment by Tollainmear** [comment]
I don't know why that there is no Error report while i double click the crazymenu today....
Maybe i had make some mistakes in my local server,so sorry to bother u these days.......
